### ISSUE TITLE
crear una nueva rama

### ISSUE THREAD

**Issue by adri157** [adri157/Adrian_git_actualizado#1]

**Comment by albertomariaperez** [comment]
Hola Adrián.
Esto está uy choreto, no tiene nada, solo 2 tonteras

**Comment by adri157** [comment]
pues por eso vamos a crear una nueva rama

**Comment by albertomariaperez** [comment]
Como que crear una nueva rama, acaso que esto es un árbol y tu eres un mono?

**Comment by adri157** [comment]
pues es si a si es

**Comment by adri157** [comment]
ya ta echo y fusionado
